#ifndef TLS_CONSTANTS_H
#define TLS_CONSTANTS_H

#define TLS_VERSION_MAJOR 0x03
#define TLS_VERSION_MINOR 0x04

#define TLS_HANDSHAKE_CLIENT_HELLO 0x01
#define TLS_HANDSHAKE_SERVER_HELLO 0x02
#define TLS_HANDSHAKE_ENCRYPTED_EXTENSIONS 0x08
#define TLS_HANDSHAKE_CERTIFICATE 0x0B
#define TLS_HANDSHAKE_CERTIFICATE_VERIFY 0x0F
#define TLS_HANDSHAKE_FINISHED 0x14

#define TLS_CONTENT_CHANGE_CIPHER_SPEC 0x15
#define TLS_CONTENT_ALERT 0x15
#define TLS_CONTENT_HANDSHAKE 0x16
#define TLS_CONTENT_APPLICATION_DATA 0x17

#define TLS_ALERT_LEVEL_WARNING 0x01
#define TLS_ALERT_LEVEL_FATAL 0x02

#define TLS_ALERT_DECODE_ERROR 0x32
#define TLS_ALERT_BAD_RECORD_MAC 0x14
#define TLS_ALERT_HANDSHAKE_FAILURE 0x28
#define TLS_ALERT_ILLEGAL_PARAMETER 0x2F
#define TLS_ALERT_PROTOCOL_VERSION 0x46

#define TLS_EXTENSION_SUPPORTED_GROUPS 0x000A
#define TLS_EXTENSION_SIGNATURE_ALGORITHMS 0x000D
#define TLS_EXTENSION_KEY_SHARE 0x0022
#define TLS_EXTENSION_PSK_KEY_EXCHANGE_MODES 0x002D

#define TLS_CIPHER_AES_128_GCM_SHA256 0x1301
#define TLS_CIPHER_AES_256_GCM_SHA384 0x1302
#define TLS_CIPHER_CHACHA20_POLY1305 0x1303

#endif